# Generated by Django 4.1.1 on 2022-09-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "dt_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시간"),
                ),
                (
                    "dt_updated",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
                ),
                ("username", models.CharField(max_length=50, verbose_name="유저네임")),
                ("password", models.CharField(max_length=255, verbose_name="비밀번호")),
                ("mobile", models.CharField(max_length=20, verbose_name="전화번호")),
                ("address", models.CharField(max_length=200, verbose_name="주소")),
                (
                    "profile_img",
                    models.ImageField(blank=True, upload_to="", verbose_name="프로필이미지"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="계정활성화")),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
