# Generated by Django 4.1.1 on 2022-09-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(default=False, verbose_name="판매자"),
        ),
    ]
