# Generated by Django 4.1.1 on 2022-09-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                blank=True, upload_to="users/images/%Y/%m/%d/", verbose_name="프로필이미지"
            ),
        ),
    ]
