# Generated by Django 4.1.1 on 2022-09-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시간"),
                ),
                (
                    "dt_updated",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="제품이름")),
                ("content", models.TextField(verbose_name="제품설명")),
                ("price", models.IntegerField(verbose_name="가격")),
                ("quantity", models.IntegerField(verbose_name="수량")),
                ("region", models.CharField(max_length=50, verbose_name="원산지")),
                (
                    "delivery_method",
                    models.CharField(max_length=30, verbose_name="배송방법"),
                ),
                ("delivery_charge", models.IntegerField(verbose_name="배송비")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opt_name", models.CharField(max_length=50, verbose_name="옵션 이름")),
                ("opt_price", models.IntegerField(verbose_name="옵션 가격")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_opt",
                        to="products.product",
                        verbose_name="제품",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, upload_to="products/images/%Y/%m/%d/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="products.product",
                        verbose_name="제품",
                    ),
                ),
            ],
        ),
    ]
